# Generated by Django 6.1.1 on 2026-09-13 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('soft', 'Soft skill'), ('hard', 'Hard skill')], default='hard', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('gained_from', models.TextField(blank=True)),
            ],
        ),
    ]
